### ISSUE TITLE
能不能在Wiki里放整段可运行的示例代码？方便理解

### ISSUE THREAD

**Issue by CAceZhou** [Smart-Space/TinUI#1]

**Comment by Smart-Space** [comment]
已添加一段简要示例代码。
实际上，TinUI.py最后的一部分代码就是使用示例。
感谢反馈，并欢迎完善！谢谢！

**Comment by CAceZhou** [comment]
呃，TinUI.py里面的示例看到了，但是Wiki好像没改啊

**Comment by CAceZhou** [comment]
![image](https://user-images.githubusercontent.com/103909046/175765838-4eff56e1-8a13-4d52-9e3c-27bf5ec76bb1.png)

**Comment by Smart-Space** [comment]
原来。。。你指readme文件，我还以为你说GitHub的wiki。我明天会更改。
之后请说详细，否则很容易造成误会或误解。

**Comment by CAceZhou** [comment]
emm谢谢提醒

**Comment by CAceZhou** [comment]
但是。。。你这写的有问题啊，前面你写的ui=TinUI(r)，后面咋成了u.add_button((5,5),text='one')
问题不大，但还是改改吧

**Comment by TotoWang-hhh** [comment]
> ![image](https://user-images.githubusercontent.com/103909046/175765838-4eff56e1-8a13-4d52-9e3c-27bf5ec76bb1.png)

看一遍：作者怎么老是这样
看两遍：？？？
看三遍：我已经迫不及待地想点进这位狠人的主页里看看ta提的其他issue了
