### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by CAceZhou** [Smart-Space/TinUI#2]
第13行报错TypeError: 'module' object is not callable
当前最新版
```
from tkinter import Tk

import TinUI  # 导入TinUI


def dop(cont):  # 处理输入框返回事件
    print(f'输入框内容为：{cont}')


r = Tk()
r.geometry('500x500+10+10')

ui = TinUI(r)
ui.pack(fill='both', expand=True)  # 填充窗口

location = (10, 10)
# 绘制若干个按钮
ui.add_title(r, location, '战争雷霆', 'black', '微软雅黑', 1, 'nw')
ui.add_button((5, 5), text='one')
ui.add_button((55, 5), text='two1')
ui.add_button((55, 40), text='two2')
ui.add_button((110, 5), text='three')

# 绘制一个输入框，并绑定到处理函数：dop
ui.add_entry((5, 180), 350, '这里用来输入', command=dop)

r.mainloop()
```
###### ps：没错又是我，其实我几个月前就打算用了，结果碰到一堆报错...

**Comment by Smart-Space** [comment]
你这是完全复制的代码吗？
我给的示例，第二行的导入是：
`from tinui.TinUI import TinUI`。
而且，add_title的第一个参数是位置，不是tk窗口类。tinui的元素第一个参数基本都是位置，这是因为tinui的组件都是在画布中绘制出来的。建议看看https://pypi.org/project/tinui/ 中对于tinui方法的说明。

**Comment by CAceZhou** [comment]
add_title(self,pos:tuple,text:str,fg='black',font='微软雅黑',size=1,anchor='nw',**kw)
呃，那这句话是不是有点问题，还是self是不用传的

**Comment by Smart-Space** [comment]
你是还没有学Python的类吗？一般没人在意类方法的实例化参数的。
如果你还没有学python类的话，那就告诉你不需要理会这个参数😄

**Comment by CAceZhou** [comment]
我终于知道为什么报错参数传多了
###### 但我依然无法理解我明明传了7个参数，但它说我传了8个...

**Comment by Smart-Space** [comment]
> 我终于知道为什么报错参数传多了
> 
> ###### 但我依然无法理解我明明传了7个参数，但它说我传了8个...

这个还是与Python的类相关知识有关，继续学习吧~~（我也是平时没事自学玩玩的）

**Comment by TotoWang-hhh** [comment]
见过离谱的，没见过这么离谱的，已经截图传给朋友看了😂
不过作为一个类都没搞懂的新手，还会上GitHub，还是比我当时厉害得多

**Comment by TotoWang-hhh** [comment]
> > 我终于知道为什么报错参数传多了
> > ###### 但我依然无法理解我明明传了7个参数，但它说我传了8个...
> 
> 这个还是与Python的类相关知识有关，继续学习吧~~（我也是平时没事自学玩玩的）

我以前报过班，当时就是想编程，也不懂。后来学了一两年，因为没时间没继续上了，再往后都是自学的。
类这块我是报班的时候学的，但是搞了很久，甚至已经停课一段时间了才彻底弄懂

**Comment by TotoWang-hhh** [comment]
> 你是还没有学Python的类吗？一般没人在意类方法的实例化参数的。 如果你还没有学python类的话，那就告诉你不需要理会这个参数😄

那不一定，我会在没文档的情况下选择看看有啥参数……

**Comment by TotoWang-hhh** [comment]
> > > 我终于知道为什么报错参数传多了
> > > ###### 但我依然无法理解我明明传了7个参数，但它说我传了8个...
> > 
> > 
> > 这个还是与Python的类相关知识有关，继续学习吧~~（我也是平时没事自学玩玩的）
> 
> 我以前报过班，当时就是想编程，也不懂。后来学了一两年，因为没时间没继续上了，再往后都是自学的。 类这块我是报班的时候学的，但是搞了很久，甚至已经停课一段时间了才彻底弄懂

特别是继承这块，我是把py玩熟了，最近看了其他继承的代码（tkwebview2）才搞懂的，以前一直不敢瞎用
