### ISSUE TITLE
将来暂停维护的时间段

### ISSUE THREAD

**Issue by Smart-Space** [Smart-Space/TinUI#3]
由于作者本人学业原因，TinUI将于2023年8月1日~2024年6月9日暂停维护。期间作者本人可能会提供少量更新。

在暂停维护的这段时间，爱好者仍然可以向TinUI发起代码合并请求，为TinUI修复BUG和添加新的功能。TinUI将一直保持开源状态。

有意作为合作者（Collaborator）的，请联系邮箱。

感谢对于TinUI的支持，谢谢。

**Comment by TotoWang-hhh** [comment]
emm……不过这种东西不应该直接往README里面写吗……

**Comment by TotoWang-hhh** [comment]
closed as completed，这是又有空了？本人盲猜高考完了？
