### ISSUE TITLE
如何设置entry的边框圆角

### ISSUE THREAD

**Issue by nicholas0707** [Smart-Space/TinUI#5]
如何设置entry的边框圆角使得输入框还有其他类似的按钮更圆？

**Comment by Smart-Space** [comment]
抱歉，TinUI目前不打算提供自定义圆角尺寸的参数（如果你的问题是表达这个意思的话）

有需要可以直接更改TinUI源码。

**Comment by nicholas0707** [comment]
> 抱歉，TinUI目前不打算提供自定义圆角尺寸的参数（如果你的问题是表达这个意思的话）
> 
> 有需要可以直接更改TinUI源码。

好的，明白了。多谢。
